### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by sentaidigital** [iCalcreator/iCalcreator#21]
Thank you for putting together this library. It is used in the [Drupal Date iCal module](https://drupal.org/project/date_ical), but since there are no releases, we have to list a URL to a specific commit.  A tagged release would be easier for users to find by just visiting GitHub, and I think they'd feel better pulling down a named version rather than a random point in time, even if that random point is as good as an official release.

**Comment by c33s** [comment]
see #7

**Comment by sentaidigital** [comment]
Thanks!

**Comment by ywarnier** [comment]
Depending on dev-master means we are depending on whatever modification is brought to the Github repository, without the ability to properly evaluate the changes. I believe that's why others are also asking for a tag.
This would be very easy to do:
- git tag -a v0.1 -m "Tagging first stable release"
- git push origin v0.1

I believe that's all, but on Github you can also go to https://github.com/iCalcreator/iCalcreator/releases, click "Add release", select the tag name and just write "First stable release".

Since there's no comment whatsoever on why *not to* tag it, I suppose this might help.

**Comment by ywarnier** [comment]
:tada:
