### ISSUE TITLE
v2.27.16 & v2.27.16.1 do not parse events

### ISSUE THREAD

**Issue by dleffler** [iCalcreator/iCalcreator#71]
Moving from v2.26.8 to v2.27.16 causes no events to be parsed/selected whereby older version returns several dozen (ESPN sports calendar)...code below
``` php
        $v = new Kigkonsult\Icalcreator\vcalendar(); // initiate new CALENDAR
        $v->setConfig('url', 'http://api.calreply.net/webcal/9bba9086-12a3-4be1-881b-c5098e8adbda');
        $v->parse();
        // get all events within period
        try {
            $eventArray = $v->selectComponents($startYear, $startMonth, $startDay, $endYear, $endMonth, $endDay, 'vevent');
        }
        catch( Exception $e ) {
            return array();
        }

**Comment by iCalcreator** [comment]
Many thanks for your 2.27.16 evaluation and bug report.

I have reproduced the 'feature' in 2.26.8 and 2.27.16.

It may depend on the Vcalendar::parse method and usage of file_get_contents,
due to usage of an url, a 'context' argument my be required.

There is a workaround, may work :

Vcalendar::setConfig( 'url', <url> );
Vcalendar::parse( null, context );

But you have to set up the 'context'.

However, the file/url calendar (read) parse (and also file writing) functionality
will be removed from iCalcreator in future versions.
You will have much better control of doing read/write calendar resources externally,
othervise it may be mixed up with (text calendar) parsing/create-calendar errors.
Separation of concerns...

But during the reproduction of this 'feature' I found and fixed another parse bug :)
It will be a 2.27.17? in a day or so.

Any other review notes on 2.27.16, hope you like it?

**Comment by tarekadam** [comment]
@iCalcreator Am I reading this right?  You're gonna remove ... read functionality  ... and write functionality... ?

**Comment by dleffler** [comment]
Actually, the issue (my issue) is calling $v->selectComponents() using a lower case $cType (vevent) which worked before, but now it MUST begin with a capital letter with the remainder being lower case (Vevent).

Code-wise, v2.27.16 does NOT perform an array_map in the assertComponentType() function as it previously did.
```
        $cType = array_map( $UCFIRST, array_map( $STRTOLOWER, $cType ) );

**Comment by iCalcreator** [comment]
Working on a fix right now.

**Comment by iCalcreator** [comment]
Now you can test 2.27.19
